### ISSUE TITLE
Cool animation yes css

### ISSUE THREAD

**Issue by CheryX** [CheryX/mmusielik.xyz#3]
yes i love css lets make some animations haha

**Comment by abitsalihu** [comment]
Hey @CheryX, I would like to help with this issue, you have any animation on mind?

**Comment by CheryX** [comment]
Hello, @abitsalihu!

Thank you for commenting on the issue, sadly this is a personal project. I am only creating issues to keep track of things to do.
I don't expect any help since it's my personal site.

Best regards,
Maciej Musielik.

**Comment by abitsalihu** [comment]
@CheryX that seems fine to me, good luck on your site. :)
